version: '3.7'

services:
    app:
        image: thetoby/mavis:latest
        volumes:
            #- ~/Projects/mavis/src/data:/usr/src/data                      # Main Mavis Data
            #- ~/Projects/mavis/src/logs:/usr/src/logs                      # Streamlit & Tensorboard Logs Location
            - ~/mavis/module_files:/usr/module_files  # Addons Location
            #- /data:/data                                                        # Any persistent data location that should be accessible
        ports:
            - 8501:8501
        # user: ${UID}
        # use gpu all
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [ gpu ]
